
## note: use title same as heading 1 in readme
##   needed for primer (default) theme to avoid duplicate title (if missing gets auto-added)

title: "Best of Ruby Gems Series"



plugins:
- jekyll-avatar
- jemoji
